language: scala

scala:
  - 2.10.2
  - 2.10.3

env:
- TERM=dumb


before_install:
  - chmod +x gradlew

install:
  - true

before_script:
  - ./gradlew setupCIWorkspace

script: ./gradlew buildNeeded

after_success:
- ./gradlew cobertura
- ./gradlew coveralls